import { Inter } from "next/font/google";
import "@/app/globals.css";
import ClientLayout from "@/components/layout";
import Header from "@/components/layout/header/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ params: { locale }, children }) {
  return (
    <html
      dir={`${["ar", "fa"].includes(locale) ? "rtl" : "ltr"}`}
      lang={locale}
    >
      <body className={inter.className}>
        <Header />
        <ClientLayout locale={locale}>{children}</ClientLayout>
      </body>
    </html>
  );
}
